[package]
name = "aws-timestream"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.107"
aws-config = "0.56.1"
aws-sdk-timestreamquery = "0.6.0"
hyper-tls = "0.5"
rusoto_core = "0.48"
rusoto_credential = "0.48"
rusoto_signature = "0.48"
dotenv = "0.15"

